# Generated by Django 4.0.1 on 2022-02-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='vendor1', max_length=255),
        ),
    ]
