# Generated by Django 4.0.2 on 2022-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productchangeslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeslog',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productchangeslog',
            name='differences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
