# Generated by Django 4.0.2 on 2022-02-15 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productchangeslog_image_productchangeslog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productchangeslog',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
