# Generated by Django 4.0.2 on 2022-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
